### ISSUE TITLE
The app crash when push back button in leitner view

### ISSUE THREAD

**Issue by mrebollob** [mrebollob/leitner-box#1]
When the user go back from leitner view the app crash.

```
Fatal Exception: java.lang.IllegalStateException: Fragment CountdownFragment{f59f0ef} not attached to a context.
       at android.support.v4.app.Fragment.requireContext(Fragment.java:696)
       at android.support.v4.app.Fragment.getResources(Fragment.java:760)
       at com.mrebollob.leitnerbox.presentation.countdown.CountdownFragment$showCountdown$1.onTick(CountdownFragment.kt:68)
       at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:130)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by mrebollob** [comment]
Fixed
